### PR TITLE
Feature/pr to bage addition

### PR DESCRIPTION
**Pull request by shuchitach**
Added a new action to create automated custom badge for feature matrix
Added workflow step in aws-eks-verify to call the action
Modified readme for the badges

Paper and Bronze badges are not yet implemented. Custom images are used in place of them

### CODE REVIEW

**Comment by mcleo-d** [comment]
Hi @shuchitach 

Thank you so much for raising this pull request 👏🏻 💯 

Can you follow the CLA signing process so we can merge in the future by following this link ... [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/13399143/173321303/216/#/?version=2)

I have also linked to the EasyCLA warning below where the CLA error is being flagged.

https://github.com/finos/compliant-financial-infrastructure/pull/216#issuecomment-1117834693
Screenshot 2022-05-06 at 06 58 12

Thanks so much for your support.

James.

**Comment by shuchitach** [comment]
image

**Comment by mcleo-d** [comment]
@mcleo-d to test EasyCLA and resolve with @eddie-knight and @shuchitach

**Comment by eddie-knight** [comment]
/easy-cla is updated and should be good to go

**Comment by shuchitach** [comment]
Hi @mcleo-d 
This call timing conflicts with my anther project call.
A 1-1 zoom call sounds good.
I am free today after 5PM BST or on Tuesday anytime. Please let me know your preferred time.

Thank you!
Shuchita

**Comment by eddie-knight** [comment]
Met with @thinkl33t and @abdullahgarcia to determine that we will not require a passing ephemeral-deploy for this PR

**Pull request merged**
