### PR TITLE
CFI OpenShift on GCP 

### PR DESCRIPTION
**Pull request by AdrianHammond**
Initial contribution for CFI for OpenShift on GCP. This provides documentation, config and code to meet the CFI Service Accelerator for OCP?

### CODE REVIEW

**Review by JuozasA — APPROVED** [review]

**Review by JuozasA — APPROVED** [review]

**Review by JuozasA — APPROVED** [review]

**Review by JuozasA — APPROVED** [review]

**Review by peterrhysthomas — APPROVED** [review]
Reviewed with @AdrianHammond, very happy to approve for merging.

Great work!

**Review by eddie-knight — APPROVED** [review]
Approving, as this is functional and very well documented with step-by-step instructions.

Still, I'll highlight that this is a highly-complex solution and it may benefit from future work to convert more of this into infrastructure as code (terraform/juju). This can be a follow-up discussion for later.

**Review by abdullahgarcia — APPROVED** [review]
Great piece of work @AdrianHammond!

**Comment by abdullahgarcia** [comment]
@AdrianHammond, let's make sure to follow up on @eddie-knight's comment above.

**Comment by AdrianHammond** [comment]
> @AdrianHammond, let's make sure to follow up on @eddie-knight's comment above.

Thanks @abdullahgarcia and @eddie-knight  - comments noted and will look to address in future PR's

**Pull request merged**
