### PR TITLE
Validation run for #189

### PR DESCRIPTION
**Pull request by thinkl33t**
Run CI to test #189 is working correctly.

### CODE REVIEW

**Comment by thinkl33t** [comment]
Requesting re-review from eddie as this makes some changes to his contribution

**Review by eddie-knight — APPROVED** [review]

**Review by peterrhysthomas — APPROVED** [review]
LGTM

**Comment by peterrhysthomas** [comment]
> LGTM

Oops - let me do this from my db account

**Review by peter-thomas-db — APPROVED** [review]
LGMT

**Pull request merged**
