### PR TITLE
Update agile documentation and README.md to include CDMC engagement and review

### PR DESCRIPTION
**Pull request by mcleo-d**
## Description

Following community socialisation of https://github.com/finos/compliant-financial-infrastructure/discussions/197#discussion-3920749 at CFI project meeting #198.

This PR updates `CFI` documentation to include how `CFI`, `OC-CDMC` and the `CDMC Technical Spec Working Group` reviews and accepts newly contributed `service approval accelerator` templates.

## Additional Document
The following document has been added to reflect the new agile workflow that includes `FINOS` and the `CDMC`. 

- `docs/agile-workflow/project-group-dependencies.md`

## Updated Documents
The following documents have been updated to reflect the new change of process. 

- `README.md` 
- `docs/agile-workflow/README.md` 

## Video Walkthrough

The following video was added to `README.md`.

https://user-images.githubusercontent.com/6029572/157091339-1f3da590-e35a-486d-a5e2-462518d65d70.mov

### CODE REVIEW

**Review by eddie-knight — CHANGES_REQUESTED** [review]
Is it beneficial to incorporate OC4CDMC so thoroughly in this documentation?

I'm concerned that in the present state it may still raise more questions than it answers (and thus cause more problems than it solves). Not only "what" and "why" is OC4CDMC... but also:

    "what is the difference?"
    "which project/community do I belong to?"
    "if the two are tightly coupled co-dependent entities, are they not actually one?"
    and more...

Could we have a dedicated session to revisit this project dichotomy?

**Comment by mcleo-d** [comment]
This PR will remain open until the modular way of architecting CFI and OC-CDMC project contributions has been fully refined.

**Review by abdullahgarcia — APPROVED** [review]
LGTM

**Comment by abdullahgarcia** [comment]
> Is it beneficial to incorporate OC4CDMC so thoroughly in this documentation?
> 
> I'm concerned that in the present state it may still raise more questions than it answers (and thus cause more problems than it solves). Not only "what" and "why" is OC4CDMC... but also:
> 
> ```
> "what is the difference?"
> "which project/community do I belong to?"
> "if the two are tightly coupled co-dependent entities, are they not actually one?"
> and more...
> ```
> 
> Could we have a dedicated session to revisit this project dichotomy?

We probably need to address this session sooner than later.

**Pull request closed without merging**
