### PR TITLE
Red Hat OpenShift Container Platform Service Approval Accelerator

### PR DESCRIPTION
**Pull request by J0EG**
New PR for review

### CODE REVIEW

**Comment by mcleo-d** [comment]
@abdullahgarcia and @peterrhysthomas 👋🏻 

Can you review this PR to make sure @J0EG is moving in the right direction?

Many thanks,

James.

**Comment by mcleo-d** [comment]
Thank you @J0EG @eddie-knight and @TLATER for resolving the commits to get EasyCLA passing. Nice work! 👏🏻 💯

**Review by abdullahgarcia — COMMENTED** [review]
@J0EG , I think the content looks good overall, but if we can have a session this week to review a few observations it would be great. Please let me know.

**Comment by abdullahgarcia** [comment]
@J0EG , a bit of detail on some of the mentioned observations:

- The documents you are submitting are ".adoc" and they should be ".md" for compatibility purposes.
- Is there a reason there are two documents instead of one?
- None of the documents dives into "shared responsibility", which is fundamental for a cloud service provider.
- There are a few formatting improvements that can be done with some sections, like "Types of network traffic flows encrypted by IPs", it could be bullet points, making it more readable.
- There are sections that contain questions in the security domain column, rather than actual security domains: e.g. "Does the service you are evaluating offer Auditing Capabilities?"

The rest of them are topic oriented and should be discussed.

**Comment by J0EG** [comment]
> @J0EG , a bit of detail on some of the mentioned observations:
> 
> * The documents you are submitting are ".adoc" and they should be ".md" for compatibility purposes.
It was previously brought up that there "may" be a preference for adoc going forward. I can convert to md if needed. 

> * Is there a reason there are two documents instead of one?
The longer one expanded-sec-details.adoc was the original doc that was originally reviewed. It was decided to keep it in the repo for reference by everyone. 

> * None of the documents dives into "shared responsibility", which is fundamental for a cloud service provider.
Fair Point, the doc OCP-SAT.adoc  was written from the vantage point of OCP running as an installed service on the cloud provider.   

> * There are a few formatting improvements that can be done with some sections, like "Types of network traffic flows encrypted by IPs", it could be bullet points, making it more readable.
Which doc? assuming expanded-sec-details.adoc? 

> * There are sections that contain questions in the security domain column, rather than actual security domains: e.g. "Does the service you are evaluating offer Auditing Capabilities?"
Will correct 
> 
> The rest of them are topic oriented and should be discussed.

**Comment by mcleo-d** [comment]
Outcomes from #139
- @mcleo-d to link this PR to the ASCII Doc issue that was raised by the team
- @abdullahgarcia to review @J0EG 's comments based on explanations
- @peter-thomas-db and @abdullahgarcia to approve and merge

**Comment by mcleo-d** [comment]
@peter-thomas-db, @abdullahgarcia and @J0EG,

Here's the GitHub Issue https://github.com/finos/cloud-service-certification/issues/70#issuecomment-840173539 that suggests the `.adoc` format as demonstrated in this PR  by @J0EG. 

I have added a `Ready to Review` label to #70 to agree the use of `.adoc` with the CSC group from this point forward.

James.

**Comment by mcleo-d** [comment]
@J0EG - Looking through the thread between you and @abdullahgarcia (https://github.com/finos/cloud-service-certification/pull/134#issuecomment-911868983), the following actions are required prior to the PR being merged.

- There are a few formatting improvements that can be done with some sections, like "Types of network traffic flows encrypted by IPs", it could be bullet points, making it more readable.
  - [ ] Which doc? assuming expanded-sec-details.adoc? @J0EG (agreed by @abdullahgarcia here https://github.com/finos/cloud-service-certification/pull/134#issuecomment-911868983)
- There are sections that contain questions in the security domain column, rather than actual security domains: e.g. "Does the service you are evaluating offer Auditing Capabilities?"
  - [ ] Will correct : @J0EG 

Many thanks! 🚀

**Pull request closed without merging**
