### PR TITLE
Canonical/Juju Service Approval Accelerator

### PR DESCRIPTION
**Pull request by pedroleaoc**
Hello CFI folks , 

Over the last few months, Canonical has been working closely  with FINOS and its community members to offer a consistent way to deploy and manage enterprise applications using Juju and Charmed Operators with a focus on Day 2 operations. The idea is to provide a software ops automation framework and toolkit that enables the DevOps teams at financial institutions to realise the benefits of rapid deployment/ testing/ using a platform that is 100% open source, vendor-agnostic and hybrid-multi-cloud ready. 

In the spirit of providing an enterprise-grade experience to FINOS members, we prepared a SAA for Juju. Any feedback is welcomed. 

*What is Juju?*
Juju is an operator lifecycle manager. 

Juju allows anyone to deploy and operate charmed operators (charms) in [any cloud](https://juju.is/docs/olm/manage-clouds)–including Kubernetes, VMs and Metal. Charms encapsulate the application + deployment and operations knowledge into one single reusable artefact. A collection of hundreds of publicly available charms is available at charmhub.io. The code necessary to integrate two applications is also encapsulated in the charm. 

There are charms currently available for two FINOS projects: Legend and Waltz. 

*Value to the FINOS community *

Juju manages the lifecycle of applications and infrastructure stacks from cloud to the edge. Juju is cloud-vendor agnostic and hybrid-multi-cloud by nature: it can manage the lifecycle of applications in public clouds, private clouds,  or on bare metal. Once bootstrapped, Juju will offer the same deployment and operations experience regardless of the cloud vendor. 

The combination of Juju and MicroK8s offer a quick yet realistic way to test and try FINOS applications running in a Kubernetes cluster. In under 10 minutes, one can provision a local Kubernetes cluster and deploy an enterprise application. 

For the FINOS developers, having an enterprise-grade deployment method used in projects across the organisation allows users to follow the best practices when deploying and managing applications.

### CODE REVIEW

**Comment by mcleo-d** [comment]
Hey @pedroleaoc

Thanks so much for the contribution. I have tagged the maintainers to help kick off the review process, plus have added to this weeks OC-CDMC agenda #194 if you're able to present the work?

James 🚀 

cc @peter-thomas-db, @abdullahgarcia, @eddie-knight, @thinkl33t

**Comment by pedroleaoc** [comment]
> if you're able to present the work?

I would be happy to provide a quick overview.

**Comment by thinkl33t** [comment]
I'd like to be part of this call :)

**Comment by mcleo-d** [comment]
**Compliant Financial Infrastructure - Canonical/Juju Service Approval Accelerator** call suggested for **Thursday 14th April at 4pm BST / 11am ET**.

**Comment by eddie-knight** [comment]
Per our last community conversation, it was suggested that we create a new directory here:

https://github.com/finos/compliant-financial-infrastructure/tree/dev/accelerators/kubernetes

That would be:
`compliant-financial-infrastructure/accelerators/kubernetes/juju`

**Comment by mcleo-d** [comment]
> Compliant Financial Infrastructure - Canonical/Juju Service Approval Accelerator call suggested for Thursday 14th April at 4pm BST / 11am ET.

This meeting is no longer needed as per #206

**Comment by mcleo-d** [comment]
Well done @pedroleaoc for your PR merge on #209 👏🏻 💯

**Pull request merged**
