### PR TITLE
Update SAA

### PR DESCRIPTION
**Pull request by abdullahgarcia**
- Change to new template/format.

### CODE REVIEW

**Comment by thinkl33t** [comment]
Should the "All guidelines provided by the aforementioned baseline are to be followed without modification or exception." also be repeated in section 3?

**Comment by abdullahgarcia** [comment]
Added that line, thanks @thinkl33t .

**Review by thinkl33t — APPROVED** [review]
LGTM

**Comment by AdrianHammond** [comment]
@abdullahgarcia  - When you say "All guidelines provided by the aforementioned baseline are to be followed without modification or exception." Does this statement include the MANUAL policies e.g. 

image

I want to be consistent with your approach in the OCP on GCP SA that I am currently updating. My plan was to call out where we were not implementing a MANUAL policy.

**Pull request merged**
