### PR TITLE
Merging dev to main

### LINKED ISSUE #277: Merge `dev` into `main`
### Description

Can the CFI maintainers merge `dev` into `main` so the `OpenSSF Progress Badge`, plus other accepted changes, reflect correctly?

Many thanks,

James.

### PR DESCRIPTION
**Pull request by eddie-knight**
Closes #277 

This pseudo-release process is still being refined.

### CODE REVIEW

**Comment by eddie-knight** [comment]
Looks like we got a pickle related to the CLA on several commits. I don't have a plan for resolving this at the moment.

**Comment by thinkl33t** [comment]
The commits that seem to have an appear to be github-created ones, and are all owned by @abdullahgarcia.  Given we have a CLA for work abdullah has done, are we able process-wise to ignore the easycla authorization and merge anyway?

**Comment by eddie-knight** [comment]
@TheJuanAndOnly99 Do you think Bob's request above is viable?

**Comment by eddie-knight** [comment]
Thanks for confirming @TheJuanAndOnly99! 

@abdullahgarcia can you set up a CLA for the offending email?

**Review by abdullahgarcia — APPROVED** [review]
LGTM

Let's move forward and address any corrections afterwards.

**Pull request merged**
