### PR TITLE
SAA AWS EKS + SAA Template Update

### PR DESCRIPTION
**Pull request by abdullahgarcia**
Hi,

Creating pull request as discussed in the Policy WG meeting today.

Thanks.

Abdullah Garcia

### CODE REVIEW

**Review by AdrianHammond — CHANGES_REQUESTED** [review]
@abdullahgarcia  - should we have the SAA version number on the updated SAA template, that way we have traceability back to which SAA version is being mapped? Apart from that LGTM.

**Comment by abdullahgarcia** [comment]
@AdrianHammond and @eddie-knight , I've addressed things with a temporal solution.

Let's move things forward so the rest of the WG can move forward too.

We should address the versioning discussion in the maintainer's meeting.

**Review by eddie-knight — APPROVED** [review]
Considering that @abdullahgarcia has noted the versioning approach is a placeholder that we will be addressing in coming weeks... LGTM.

**Review by AdrianHammond — APPROVED** [review]
Approved

**Pull request merged**
